/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "59441ff6b83620085b008f413dc0fd6e8023730f"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
