/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "e17410ba17bd1feafda0d15d9588f16fa3066253"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
